version: '2'
services:
  database-server:
    container_name: database-server
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: guest
    networks:
      - spring-cloud-network
    expose:
      - 5432
  config-server:
    container_name: config-server
    image: config-server:latest
    expose:
      - 8888
    ports:
      - 8888:8888
    networks:
      - spring-cloud-network
  eureka-server:
    container_name: eureka-server
    image: eureka-server:latest
    expose:
      - 8761
    ports:
      - 8761:8761
    networks:
      - spring-cloud-network
  students:
    container_name: students
    image: students:latest
    environment:
      SPRING_APPLICATION_JSON: '{"spring":{"cloud": {"config":{"uri": "http://config-server:8888"}}}}'
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - "config-server"
      - "eureka-server"
      - "database-server"
    networks:
      - spring-cloud-network
    links:
      - config-server:config-server
      - eureka-server:eureka-server
      - database-server:database-server
  gateway:
    container_name: gateway
    image: gateway:latest
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - spring-cloud-network
    depends_on:
      - "eureka-server"
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'
networks:
  spring-cloud-network:
    driver: bridge

